httpTimeout: 600000
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"

# Add these for EAS compatibility:
enableImmutableInstalls: false
unsafeHttpWhitelist:
  - "registry.npmjs.org"