name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd api
          pytest


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Create SSH key
        run: |
          printf "%s" "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2 (Fixed)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF

            cd netmedika
            git pull origin main

            docker build -t netmedika-app ./api

            docker stop netmedika || true
            docker rm netmedika || true

            echo "Running migrations..."
            docker run --rm -e DATABASE_URL=$DATABASE_URL netmedika-app alembic upgrade head

            echo "Starting app..."
            docker run -d -p 8000:8000 -e DATABASE_URL=$DATABASE_URL --name netmedika netmedika-app

          EOF